server:
  port: 0

spring:
  mvc:
    problemdetails:
      enabled: true
  mongodb:
    uri: "mongodb://root:ZrjzWhPC_uEbHkGpXF4GiWLDVmC4SChTHRahTApXgvduycqG@887a4b5c-bb10-409f-a140-554428ce6c25.asia-southeast1.firestore.goog:443/db-quickhire?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false"


eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
