server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://root:mongodb@localhost:13500/quickhire_jobs?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka