server:
  port: 8082

spring:
  mvc:
    problemdetails:
      enabled: true
  mongodb:
    host: localhost
    port: 13500
    database: quickhire_jobs
    username: root
    password: mongodb
    authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
