server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:12500/quickhire_users
    username: postgres
    password: psql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}