server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:12500/quickhire_users
    username: postgres
    password: psql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
