server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka